<?php

use App\Models\Room;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [
            [
                'host_id' => 1,
                'building_id' => 1,
                'name' => 'P101',
                'price' => 3000000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 1,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 1,
                'name' => 'P201',
                'price' => 3000000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 1,
                'name' => 'P202',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 2,
                'name' => 'P101',
                'price' => 3000000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 1,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 2,
                'name' => 'P202',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 2,
                'name' => 'P201',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 3,
                'name' => 'P101',
                'price' => 3000000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 1,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 3,
                'name' => 'P202',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 3,
                'name' => 'P201',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 4,
                'name' => 'P101',
                'price' => 3000000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 1,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 4,
                'name' => 'P202',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
            [
                'host_id' => 1,
                'building_id' => 4,
                'name' => 'P201',
                'price' => 3500000,
                'room_category_id' => 1,
                'utility_id' => '',
                'acreage' => 35,
                'max_people' => 4,
                'floors' => 2,
                'status' => 2,
                'active' => 2,
            ],
        ];
        foreach($datas as $data){
            $room =  Room::create($data);
        }
    }
}
