<?php

if (!defined('STATUS_ACCOUNT_USER_REGISTER')) define('STATUS_ACCOUNT_USER_REGISTER', 0);
if (!defined('STATUS_ACCOUNT_USER_ACTIVE')) define('STATUS_ACCOUNT_USER_ACTIVE', 1);
if (!defined('STATUS_ACCOUNT_USER_NOT_ACTIVE')) define('STATUS_ACCOUNT_USER_NOT_ACTIVE', 2);

if (!defined('STATUS_ACCOUNT_CUSTOMER_REGISTER')) define('STATUS_ACCOUNT_CUSTOMER_REGISTER', 0);
if (!defined('STATUS_ACCOUNT_CUSTOMER_ACTIVE')) define('STATUS_ACCOUNT_CUSTOMER_ACTIVE', 1);
if (!defined('STATUS_ACCOUNT_CUSTOMER_NOT_ACTIVE')) define('STATUS_ACCOUNT_CUSTOMER_NOT_ACTIVE', 2);

// if (!defined('STATUS_ACCOUNT_ADMIN_REGISTER')) define('STATUS_ACCOUNT_ADMIN_REGISTER', 0);
if (!defined('STATUS_ACCOUNT_ADMIN_NOT_ACTIVE')) define('STATUS_ACCOUNT_ADMIN_NOT_ACTIVE', 0);
if (!defined('STATUS_ACCOUNT_ADMIN_ACTIVE')) define('STATUS_ACCOUNT_ADMIN_ACTIVE', 1);



if (!defined('STATUS_POST_DRAFT')) define('STATUS_POST_DRAFT', 0);
if (!defined('STATUS_POST_PUBLIC')) define('STATUS_POST_PUBLIC', 1);

if (!defined('STATUS_COMMENT_PUBLIC')) define('STATUS_COMMENT_PUBLIC', 1);
if (!defined('STATUS_COMMENT_APPROVE')) define('STATUS_COMMENT_APPROVE', 0);

if (!defined('UTILITY_ROOM')) define('UTILITY_ROOM', 'room');
if (!defined('UTILITY_BUILDING')) define('UTILITY_BUILDING', 'building');

if (!defined('MESSAGE_CUSTOMER')) define('MESSAGE_CUSTOMER', 1);
if (!defined('MESSAGE_HOST')) define('MESSAGE_HOST', 2);
